/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import communication.CommunicationController;
import domain.TezinaVezbe;
import domain.Vezba;
import java.awt.Window;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.IIOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Marija
 */
public class RadSaVezbamaDetailsJPanel extends javax.swing.JPanel {

    Vezba ucitanaVezba;

    public Vezba getUcitanaVezba() {
        return ucitanaVezba;
    }

    public void setUcitanaVezba(Vezba ucitanaVezba) {
        this.ucitanaVezba = ucitanaVezba;
    }

    /**
     * Creates new form RadSaVezbamaDetailsJPanel
     */
    public RadSaVezbamaDetailsJPanel() {
        initComponents();
        prepareView();
    }

    private void prepareView() {
        try {
            
            jComboBox1.removeAllItems();
            jComboBox1.addItem(TezinaVezbe.Laka);
            jComboBox1.addItem(TezinaVezbe.Srednja);
            jComboBox1.addItem(TezinaVezbe.Teska);
            Vezba v = (Vezba) CommunicationController.getInstance().getSavedData();
            setUcitanaVezba(CommunicationController.getInstance().getVezba(v));
            
            
            
                        
            jTextField1.setText("");
            jTextField1.setText(ucitanaVezba.getNaziv());
            jTextArea1.setText(ucitanaVezba.getOpis());
            if (ucitanaVezba.isMoguceSamoUTeretani()) {
                jRadioButton1.setSelected(true);
                jRadioButton2.setSelected(false);
            }else{
            jRadioButton2.setSelected(true);
            jRadioButton1.setSelected(false);
            }
            jTextField2.setText(ucitanaVezba.getPutDoFajla());
            switch (ucitanaVezba.getTezinaVezbe()) {
                case Laka:
                    jComboBox1.setSelectedIndex(0);
                    break;
                    case Srednja:
                    jComboBox1.setSelectedIndex(1);
                    break;
                    case Teska:
                    jComboBox1.setSelectedIndex(2);
                    break;
                default:
                    throw new AssertionError();
            }
            
            BufferedImage myPicture = ImageIO.read(new File(ucitanaVezba.getPutDoFajla()));
            ImageIcon ii = new ImageIcon(myPicture);
            imageJLabel.setIcon(ii);
            
            

        } catch (IIOException ex) {
            Logger.getLogger(RadSaVezbamaDetailsJPanel.class.getName()).log(Level.SEVERE, null, ex);
            BufferedImage myPicture;
            try {
                myPicture = ImageIO.read(new File("files\\noImage.jpg"));
                ImageIcon ii = new ImageIcon(myPicture);
                imageJLabel.setIcon(ii);
                
            } catch (IOException ex1) {
                Logger.getLogger(RadSaVezbamaDetailsJPanel.class.getName()).log(Level.SEVERE, null, ex1);
            }
       
        }
        
        catch (Exception ex) {
            Logger.getLogger(RadSaVezbamaDetailsJPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        azurirajVezbuJButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        imageJPanel = new javax.swing.JPanel();
        imageJLabel = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Brisanje i izmena vezbi"));

        jLabel4.setText("Fajl Slika:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel5.setText("Tezina Vezbe:");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Da");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Ne");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Naziv:");

        jLabel2.setText("Opis:");

        jLabel3.setText("Moguca samo u teretani:");

        azurirajVezbuJButton.setText("Azuriraj Vezbu");
        azurirajVezbuJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                azurirajVezbuJButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Obrisi Vezbu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        imageJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout imageJPanelLayout = new javax.swing.GroupLayout(imageJPanel);
        imageJPanel.setLayout(imageJPanelLayout);
        imageJPanelLayout.setHorizontalGroup(
            imageJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        imageJPanelLayout.setVerticalGroup(
            imageJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(azurirajVezbuJButton)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton2))
                            .addComponent(jScrollPane1)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(azurirajVezbuJButton)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(imageJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void azurirajVezbuJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_azurirajVezbuJButtonActionPerformed
          try {
           Vezba v = new Vezba();
           v.setiDVezba(ucitanaVezba.getiDVezba());
           v.setNaziv(jTextField1.getText());
           v.setOpis(jTextArea1.getText());
              if (jRadioButton1.isSelected()) {
                  v.setMoguceSamoUTeretani(true);
              }
              if (jRadioButton2.isSelected()) {
                  v.setMoguceSamoUTeretani(false);
              }
              v.setPutDoFajla(jTextField2.getText().replace("\\", "\\\\"));
              v.setTezinaVezbe((TezinaVezbe)jComboBox1.getSelectedItem());
           
            CommunicationController.getInstance().updateVezba(v);
            JOptionPane.showMessageDialog(this, "Vezba azurirana", "Obavestenje", JOptionPane.PLAIN_MESSAGE);
            prepareView();
        } catch (Exception ex) {
            Logger.getLogger(RadSaKorisnicimaDetailsJPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Greska pri cuvanju vezbe " +ex, "Greska", JOptionPane.ERROR_MESSAGE);
            prepareView();
        }
       
    }//GEN-LAST:event_azurirajVezbuJButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            CommunicationController.getInstance().deleteVezba(ucitanaVezba);
            JOptionPane.showMessageDialog(this, "Vezba obrisana", "Obavestenje", JOptionPane.PLAIN_MESSAGE);
            
            JComponent comp = (JComponent) this;
            Window win = SwingUtilities.getWindowAncestor(comp);
            win.dispose();
        }
         catch (Exception ex) {
            Logger.getLogger(RadSaKorisnicimaDetailsJPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Sistem ne može da obriše vežbu " +ex, "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton azurirajVezbuJButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel imageJLabel;
    private javax.swing.JPanel imageJPanel;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<Object> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
